---
name: Build Alpine binaries

on:
  workflow_dispatch:

# We do not want a new staging build to run whilst we are releasing the current staging build.
# We also do not want multiples to run for the same version.
concurrency: build-alpine-binaries

permissions:
  contents: read

jobs:
  build-release:
    permissions:
      contents: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_version: [3.22, 3.23, 3.24]
    container:
      image: alpine:${{matrix.alpine_version}}
    steps:
      - name: Install dependencies
        run: apk update && apk add --no-cache musl-dev linux-headers fts fts-dev openssl-dev openssl-libs-static flex bison yaml yaml-dev ninja git cmake ca-certificates gcc g++ make zip
      - name: Checkout code
        env:
          FLUENT_BIT_VERSION: ${{github.ref_name}}
        run: git clone --depth 1 --branch ${FLUENT_BIT_VERSION} https://github.com/DoumanAsh/fluent-bit.git
      - name: Get version
        id: version
        run: |
          VERSION=$(head -n 20 fluent-bit/dockerfiles/Dockerfile | grep RELEASE_VERSION | cut -d '=' -f 2)
          echo "value=$VERSION" >> "$GITHUB_OUTPUT"
          echo "### 🚀 Build $VERSION binaries" >> $GITHUB_STEP_SUMMARY
      - name: Install dependencies
        run: apk update && apk add --no-cache musl-dev linux-headers fts fts-dev openssl-dev flex bison yaml yaml-dev ninja git cmake ca-certificates gcc g++ make
      - name: Build
        run: |
          mkdir -p fluent-bit/build &&   \
          cd fluent-bit/build &&         \
          cmake ..                       \
          -DFLB_JEMALLOC=On              \
          -DFLB_OUT_KAFKA_REST=Off       \
          -DFLB_OUT_KAFKA=Off            \
          -DFLB_EXAMPLES=Off             \
          -DFLB_SIGNV4=Off               \
          -DFLB_AWS=Off                  \
          -DFLB_FILTER_AWS=Off           \
          -DFLB_OUT_S3=Off               \
          -DFLB_OUT_KINESIS_FIREHOSE=Off \
          -DFLB_OUT_KINESIS_STREAMS=Off  \
          -DFLB_OUT_CLOUDWATCH_LOGS=Off  \
          -DFLB_OUT_BIGQUERY=Off         \
          -DFLB_OUT_GCS=Off              \
          -DFLB_KAFKA=Off                \
          -DFLB_ZIG=Off                  \
          -DFLB_TLS=Yes                  \
          -DFLB_HTTP_SERVER=Yes          \
          -DCMAKE_C_STANDARD=17          \
          -DCMAKE_BUILD_TYPE=Release     \
          -DFLB_LUAJIT=on                \
          -DFLB_IN_PODMAN_METRICS=On     \
          -DFLB_IN_SYSTEMD=On            \
          -DFLB_OUT_DATADOG=On           \
          -DFLB_OUT_AZURE=Off            \
          -DFLB_OUT_AZURE_KUSTO=Off      \
          -DFLB_OUT_PGSQL=Off            \
          -DFLB_OUT_SLACK=Off            \
          -DFLB_OUT_STACKDRIVER=Off      \
          -DFLB_OUT_SPLUNK=Off           \
          -DFLB_OUT_TD=Off               \
          -DFLB_SHARED_LIB=Off           \
          -DFLB_DEBUG=Off                \
          -DFLB_RELEASE=on               \
          -DYAML_DECLARE_STATIC=on       \
          -DFLB_PREFER_SYSTEM_LIB_ZSTD=on\
          -DFLB_TESTS_INTERNAL=Off       \
          -DFLB_TESTS_RUNTIME=Off        \
          -DCMAKE_INSTALL_PREFIX=/usr    \
          -DCMAKE_INSTALL_LIBDIR=lib     \
          -DFLB_WITHOUT_flb-it-pack=Yes  \
          -DFLB_WITHOUT_flb-it-utils=Yes \
          -DFLB_WITHOUT_flb-it-aws_util=Yes \
          -DFLB_WITHOUT_flb-it-aws_credentials_process=Yes \
          -G Ninja \
          && cmake --build . \
          && ninja install \
          && mkdir /etc/fluent-bit/ \
          && mv /usr/etc/fluent-bit/parsers.conf /etc/fluent-bit/parsers.conf \
          && mv /usr/etc/fluent-bit/plugins.conf /etc/fluent-bit/plugins.conf

      - name: Pack release
        run: zip -9 -j fluent-bit-x86_64-alpine${{matrix.alpine_version}}.zip /usr/bin/fluent-bit /etc/fluent-bit/parsers.conf /etc/fluent-bit/plugins.conf /usr/bin/luajit

      - name: Create or Update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.value }}
          name: "fluent-bit v${{ steps.version.outputs.value }}"
          body: "Alpine binaries of fluent-bit excluding cloud features"
          artifacts: "fluent-bit-x86_64-alpine${{matrix.alpine_version}}.zip"
          allowUpdates: true
          updateOnlyUnreleased: false
